import '@/styles/globals.scss';

export const metadata = {
  title: 'Bocado de Café',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
